Car_yard_exrices
Arielgithub101/Finel_exercise_ pull request #1
Opened 2022-08-09 13:27 UTC by Arielgithub101

2022-08-09 15:03 UTC, manorbar requested changes

2022-08-09 15:03 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            print(car.car_info())
this logic is repeated, think of a better way to do this

2022-08-09 15:03 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            return print('car not found')
read about better ways in python to filter a list

2022-08-11 14:20 UTC, Arielgithub101 commented on Car_Yard/CarClass.py
> +        cls.id_car += 1
done

2022-08-11 14:20 UTC, Arielgithub101 commented on Car_Yard/CarClass.py
> +
done

2022-08-11 14:21 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    all_cars:List[Car] = []
done

2022-08-11 14:21 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +class CarYard():
done

2022-08-11 14:21 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    all_cars:List[Car] = []
done

2022-08-11 14:21 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    def add_car(self) -> None:
done

2022-08-11 14:22 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +                    print("invalid option,try again")
done , i move it to main,(it was more for me to check if the methoddd works ok

2022-08-11 14:22 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +        return print('Car not found')
done

2022-08-11 14:23 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +        return print('Car not found')
done --- > dictionary

2022-08-11 14:23 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            return print('no gas car where founded')
done

2022-08-11 14:24 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            print(car.car_info())
fix it , turnd it to a function

2022-08-11 14:31 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            return print('car not found')
i did class function for this,
Maybe there's a better way but I haven't found one yet

2022-08-14 07:29 UTC, manorbar requested changes

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarClass.py
> +
format the file

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +    def __init__(self, all_car_dict: Dict[int, Car] = {}):
why is there a default value?

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            return print('car License plate already in system,try again')
```
if key in dict:
```
is cleaner

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            return print('car not found')
try to think of a better way to do this without accessing the same key twice

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +    def remove_car(self, id: int) -> None:
don't use `id` as an argument name in functions - is shadows the built in python `id` 
also, take a look at warnings PyCharm gives you

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            return print('car not found')
same here
also, why do you need `return` here?

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarClass.py
> +
not done

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +    def disply_info_by_param(cls, info_dict: Dict[int, Car], param):
why does this need to be a class method which receives a property of the instance?

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +                    item.car_info()
think of a way to do this without repeating like you did here

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +    def disply_info_by_param(cls, info_dict: Dict[int, Car], param):
this function seem to do a lot and it causes a pretty confusing code, break it up

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +                    item.car_info()
what if tomorrow the client wants to add another type of car? developer wouldn't think this code needs to change and even if he does this `if` would get really ugly really fast

2022-08-14 07:29 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +from CarClass import Car
python conventions is to not name files with capital letters

2022-08-14 11:11 UTC, Arielgithub101 commented on Car_Yard/CarClass.py
> +
done for reall

2022-08-14 11:15 UTC, Arielgithub101 commented on Car_Yard/CarClass.py
> +
done

2022-08-14 11:27 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    def __init__(self, all_car_dict: Dict[int, Car] = {}):
The question does not specify whether the car yard is empty at the beginning or not,
Therefore if the user does not send data the defult value is empty dict

2022-08-14 11:27 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            return print('car License plate already in system,try again')
done

2022-08-14 11:27 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            return print('car not found')
done

2022-08-14 11:29 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    def remove_car(self, id: int) -> None:
the pyCharm didn't give me any warnings about using it (the id..)
 but I changed it anyway

2022-08-14 11:30 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            return print('car not found')
done

2022-08-14 11:30 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    def disply_info_by_param(cls, info_dict: Dict[int, Car], param):
done,

2022-08-14 11:31 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    def disply_info_by_param(cls, info_dict: Dict[int, Car], param):
done,
I found a solution regarding the type of car but the color and this year remained the same

2022-08-14 11:32 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +                    item.car_info()
done

2022-08-14 11:32 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +from CarClass import Car
done

2022-08-14 12:05 UTC, manorbar requested changes

2022-08-14 12:05 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            print('car License plate already in system,try again')
nice change
one minor tweak I would do is to first check if the car exists and if so, exit the function (with exception ore just return)
and after that just update the dict with the new car
it would remove the `if not` and `else` and would look a lot better in my opinion
(try to think about this every time you do a `if not...`, a lot of times it is a sign of a design that could be improved

2022-08-14 12:05 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            print('try again invalid id number')
nice!
two minor changes:  
1. better argument name to indicate deletion
2. the error message isn't really good, the id you get in this case is valid, it just doesn't exist in the current state

2022-08-14 12:10 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +    def remove_car(self, id: int) -> None:
weird, it gives for me

2022-08-14 12:21 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    def __init__(self, all_car_dict: Dict[int, Car] = {}):
done

2022-08-14 12:28 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +from CarClass import Car
I am trying to rename the file but it's causing me problems when i try to push it to the github, i don't understand why  but Im working to understand it ,So I'll change it later

2022-08-14 12:28 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +                item.car_info()
done

2022-08-14 12:29 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    def display_all_cars_by_type(self, type_car) -> None:
done

2022-08-14 12:31 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +        for item in self.all_car_dict.values():
Does it matter?
i changed it to more meaningful name if that's the intention

2022-08-14 12:37 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            print('car License plate already in system,try again')
done

2022-08-14 12:39 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            print('try again invalid id number')
done

2022-08-14 12:52 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +    def __init__(self, all_car_dict: Dict[int, Car] = {}):
seems like you removed the default value, was that intended?

2022-08-14 12:53 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +        for item in self.all_car_dict.values():
naming is always important :)

2022-08-14 12:54 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +        if new_car.id_plate in self.all_car_dict.keys():
no need to do `.keys`
you can just do `if key in dict:`

2022-08-14 12:54 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            print('try again invalid id number')
still `id_check`

2022-08-14 13:46 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    def __init__(self, all_car_dict: Dict[int, Car] = {}):
sorry ,forgot to send the correct one...

2022-08-14 13:46 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +        if new_car.id_plate in self.all_car_dict.keys():
ddone

2022-08-14 13:47 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            print('try again invalid id number')
done

2022-08-14 14:07 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +    def __init__(self, all_car_dict: Dict[int, Car] = {}):
so you intended to remove the option to init the car yard with cars?

2022-08-14 14:08 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            print('try again invalid id number')
still...

2022-08-14 14:12 UTC, manorbar requested changes

2022-08-14 14:12 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +        self.display_all_cars_by_type('hybrid')
one last thing for this exercise (at least for me)
add an enum for car types

2022-08-15 12:14 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +        self.display_all_cars_by_type('hybrid')
made enum, is this Was that the intention?

2022-08-15 12:28 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +    def __init__(self, all_car_dict: Dict[int, Car] = {}):
fix it .. i think 
I didn't understand what you meant by none so I made if statment instead, 
and if the user sent info, then the constractur will be reset with this data

2022-08-15 12:29 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            print('try again invalid id number')
done,

2022-08-15 12:29 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +        self.display_all_cars_by_type('hybrid')
made enum ,
is that what you meant?

2022-08-15 12:40 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +    def __init__(self, all_car_dict: Dict[int, Car] = {}):
exactly what I meant, nice

2022-08-15 13:12 UTC, manorbar requested changes

2022-08-15 13:12 UTC, manorbar commented on Car_Yard/CarClass.py
> +        self.type_car: str = type_car
the type of `type_car` should be the enum

2022-08-15 13:12 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +                car.car_info()
should be a private method

2022-08-15 13:12 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +        self.display_all_cars_by_type(CarTypes.hybrid.name)
change this after you change `Car`

2022-08-15 13:12 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +                item.car_info()
`for car in...`

2022-08-15 13:12 UTC, manorbar commented on Car_Yard/main.py
> +print(m.value)
take a look at your code before pushing, this should not be submitted for review

2022-08-16 07:20 UTC, Arielgithub101 commented on Car_Yard/main.py
> +print(m.value)
done

2022-08-16 07:20 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +                item.car_info()
done

2022-08-16 07:20 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +        self.display_all_cars_by_type(CarTypes.hybrid.name)
done

2022-08-16 07:21 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +                car.car_info()
done

2022-08-16 07:23 UTC, Arielgithub101 commented on Car_Yard/CarClass.py
> +        self.type_car: str = type_car
done , 
what do you think of this code?
Im not sure abut it..

2022-08-16 11:38 UTC, manorbar requested changes

2022-08-16 11:38 UTC, manorbar commented on Car_Yard/ElectricClass.py
> +        super().__init__(price, year_of_prod, mile, color, company, id_plate, CarTypes.gas)
should be electric, be careful with copy pastes

2022-08-16 11:38 UTC, manorbar commented on Car_Yard/CarClass.py
> +        self.type_car: CarTypes = type_car
rename to `type`

2022-08-16 11:38 UTC, manorbar commented on Car_Yard/CarYardClass.py
> +            print('car not found')
would be slightly better to get the key without get and `except KeyError`

2022-08-16 12:03 UTC, Arielgithub101 commented on Car_Yard/CarYardClass.py
> +            print('car not found')
done

2022-08-16 12:03 UTC, Arielgithub101 commented on Car_Yard/CarClass.py
> +        self.type_car: CarTypes = type_car
done

2022-08-16 12:03 UTC, Arielgithub101 commented on Car_Yard/ElectricClass.py
> +        super().__init__(price, year_of_prod, mile, color, company, id_plate, CarTypes.gas)
done

2022-08-16 12:25 UTC, manorbar commented on Car_Yard/CarClass.py
> +        self.type_car: str = type_car
looks good

2022-08-16 12:27 UTC, manorbar approved these changes

2022-08-16 14:17 UTC, merged